version: '3'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8081:8081"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"